### ISSUE TITLE
[BUG] Intellisense throwing errors for mixins

### ISSUE THREAD

**Issue by michael-letcher** [mrmlnc/vscode-less#48]
Throwing errors due to using this mixin that uses a pram as a function

```less
.responsive(@maxWidth, @rules) {
    @media only screen and (max-width: @maxWidth) {
        @rules();
    }
}
```

Errors when using like so. (** ... ** showing where it is showing an error)
```less
.responsive(@grid-md-max, {
    **.**grid-item(@column-start: @column-start-md; **@column-end**: @column-end-md; @row-start: @row-start-md; @row-end: @row-end-md;
               @columns: @columns-md; @rows: @rows-md
    **)**;
**}**);
```
