### ISSUE TITLE
Autocomplete failed while using pattern-matching mixins

### ISSUE THREAD

**Issue by tianzhich** [mrmlnc/vscode-less#57]
I used [pattern-matching mixins](https://lesscss.org/features/#mixins-feature-pattern-matching) in some of my less files. But all the smart prompts for variables and mixins of these files have disappeared.

For example:

```// mixin.less```
```less
.mixin(dark, @color) {
  color: darken(@color, 10%);
}
.mixin(light, @color) {
  color: lighten(@color, 10%);
}
.mixin(@_, @color) {
  display: block;
}
```
