### ISSUE TITLE
Support suggestions for NodeType.Declarations

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-less#9]
```less
.test() {
	@help: "me";

	.loop() {
		// code
	}

	.loop();
	// Here should be .loop and @help
}
```
